version: "3.8"

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-admin}
      POSTGRES_USER: ${POSTGRES_PASSWORD:-admin}


  pgadmin:
    image: elestio/pgadmin:latest
    restart: always
    ports:
      - "8050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@localhost.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    depends_on:
      - db

  chromadb:
    image: chromadb/chroma:latest
    restart: always
    ports:
      - "8080:8000"
